name = "traffic-worker-v0"
main = "src/index.js"
compatibility_date = "2026-02-19"
workers_dev = true

[vars]
WORKER_API_KEY = "dev_key_2026_kaito_abc123"
ALLOWED_ORIGINS = "https://traffic-worker-v0.kaitomoga0316.workers.dev,https://liff.line.me"
GEMINI_MODEL = "gemini-1.5-flash"
IDEMPOTENCY_TTL_SECONDS = "86400"
WEBHOOK_EVENT_TTL_SECONDS = "86400"
LINE_RICHMENU_ID_REGISTERED = "richmenu-79334ff2600b5f8c8bd6c60e95f00ba6"
LINE_RICHMENU_ID_UNREGISTERED = "richmenu-887950d6199cf7c72c53a490e2a3436b"

[triggers]
crons = ["0 1 * * *"]

[[kv_namespaces]]
binding = "IDEMPOTENCY_KV"
id = "36c930ac6ddb4676a648a997a71945fa"
preview_id = "8f69a945fcc6486e871c150a923dde47"

[[durable_objects.bindings]]
name = "IDEMPOTENCY_LOCK"
class_name = "IdempotencyLockDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["IdempotencyLockDurableObject"]
